# Generated by Django 6.0.1 on 2026-01-29 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferringHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_inside_davao_city', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('waiting', 'Waiting'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='routine', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chief_complaint', models.TextField()),
                ('pertinent_history', models.TextField()),
                ('pertinent_physical_exam', models.TextField()),
                ('bp', models.CharField(max_length=20, verbose_name='Blood Pressure')),
                ('hr', models.IntegerField(verbose_name='Heart Rate')),
                ('rr', models.IntegerField(verbose_name='Respiratory Rate')),
                ('temp', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temperature')),
                ('o2_sat', models.IntegerField(verbose_name='O2 Saturation')),
                ('gcs_score', models.CharField(max_length=50, verbose_name='GCS Score or AVPU')),
                ('o2_support', models.CharField(max_length=100, verbose_name='O2 Support')),
                ('admission_status', models.CharField(choices=[('emergency_room', 'Emergency Room'), ('ward', 'Ward'), ('intensive_care_unit', 'Intensive Care Unit')], max_length=30)),
                ('rtpcr_result', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('not_done', 'Not Done')], max_length=20)),
                ('working_impression', models.TextField()),
                ('management_done', models.TextField()),
                ('patient_category', models.CharField(choices=[('new_patient', 'New Patient of SPMC'), ('known_patient', 'Old or Known Patient of SPMC')], max_length=20)),
                ('hrn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hospital Record Number')),
                ('patient_full_name', models.CharField(max_length=200)),
                ('current_address', models.TextField()),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('other_specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('reason_for_referral', models.TextField()),
                ('referrer_name', models.CharField(max_length=200)),
                ('referrer_profession', models.CharField(max_length=100)),
                ('referrer_cellphone', models.CharField(max_length=20)),
                ('mode_of_transportation', models.CharField(max_length=100)),
                ('consent_secured', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_referrals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_referrals', to=settings.AUTH_USER_MODEL)),
                ('referring_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.referringhospital')),
                ('specialty_needed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.specialty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='referral_documents/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='referrals.referral')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='referrals.referral')),
            ],
            options={
                'verbose_name_plural': 'Referral Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TransitInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watcher_name', models.CharField(max_length=200)),
                ('watcher_age', models.IntegerField()),
                ('relation_to_patient', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('escort_nurse', models.CharField(max_length=200)),
                ('driver', models.CharField(max_length=200)),
                ('referring_md', models.CharField(max_length=200)),
                ('referring_facility', models.CharField(max_length=200)),
                ('latest_vs', models.TextField(verbose_name='Latest Vital Signs')),
                ('gcs', models.CharField(max_length=50, verbose_name='GCS')),
                ('time_ambulance_left', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transit_info', to='referrals.referral')),
            ],
        ),
    ]
