# Generated by Django 6.0.1 on 2026-01-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitinfo',
            name='driver',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transitinfo',
            name='escort_nurse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transitinfo',
            name='gcs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GCS'),
        ),
        migrations.AlterField(
            model_name='transitinfo',
            name='latest_vs',
            field=models.TextField(blank=True, null=True, verbose_name='Latest Vital Signs'),
        ),
        migrations.AlterField(
            model_name='transitinfo',
            name='referring_facility',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transitinfo',
            name='referring_md',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transitinfo',
            name='time_ambulance_left',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
