# Generated by Django 6.0.1 on 2026-01-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0005_update_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='is_emergent',
            field=models.BooleanField(default=False),
        ),
    ]
