# Generated by Django 6.0.1 on 2026-02-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0006_add_is_emergent_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Scheduled appointment date for OPD', null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Scheduled appointment time for OPD', null=True),
        ),
    ]
