# Generated by Django 6.0.1 on 2026-02-03 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0008_add_assigned_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferrerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('referrer_type', models.CharField(choices=[('doctor', 'Doctor / Medical Professional'), ('hospital_employee', 'Authorized Hospital Employee'), ('hospital_account', 'Hospital Account'), ('other', 'Other')], max_length=30)),
                ('position', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate_hospitals', models.ManyToManyField(blank=True, related_name='affiliated_referrers', to='referrals.referringhospital')),
                ('specialties', models.ManyToManyField(blank=True, related_name='referrers', to='referrals.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferrerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('official_id', 'Official Registered ID'), ('legal_document', 'Legal Document (Hospital)'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='referrer_documents/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='referrals.referreraccount')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
