# Generated by Django 6.0.1 on 2026-02-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0009_referreraccount_referrerdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='referreraccount',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referreraccount',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referreraccount',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
