# Generated by Django 6.0.1 on 2026-02-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0010_referreraccount_address_referreraccount_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cellphone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_inside_davao',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('edcc_personnel', 'EDCC Personnel'), ('call_triage', 'EDMAR/EDHO (Call Triage)'), ('admin', 'Administrator'), ('referrer', 'Referrer')], default='edcc_personnel', max_length=20),
        ),
    ]
