# Generated by Django 6.0.1 on 2026-02-04 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0011_add_referrer_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='transferred_at',
            field=models.DateTimeField(blank=True, help_text='When referral was transferred to triage', null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='transferred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='triaged_at',
            field=models.DateTimeField(blank=True, help_text='When triage decision was made', null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='triaged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
