# Generated by Django 6.0.1 on 2026-02-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0012_referral_transferred_at_referral_transferred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='transit_decision',
            field=models.CharField(blank=True, choices=[('now', 'Transport Now'), ('scheduled', 'Scheduled Transport')], help_text="Referrer's decision on when to transport patient", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='transit_decision_at',
            field=models.DateTimeField(blank=True, help_text='When referrer made transit decision', null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='transit_scheduled_date',
            field=models.DateField(blank=True, help_text='When referrer wants to schedule transport', null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='transit_scheduled_time',
            field=models.TimeField(blank=True, help_text='Time referrer wants to schedule transport', null=True),
        ),
    ]
