# Generated by Django 6.0.1 on 2026-02-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0012_referral_transferred_at_referral_transferred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_barangay',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_doh_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_province',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_view_only',
            field=models.BooleanField(default=False),
        ),
    ]
