# Generated by Django 6.0.1 on 2026-02-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0013_add_transit_decision_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='referreraccount',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
