# Generated by Django 6.0.1 on 2026-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0014_referreraccount_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('edcc_personnel', 'EDCC Personnel'), ('call_triage', 'EDMAR/EDHO (Call Triage)'), ('his_department', 'HIS Department'), ('admin', 'Administrator'), ('referrer', 'Referrer')], default='edcc_personnel', max_length=20),
        ),
    ]
