# Generated by Django 6.0.1 on 2026-02-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0015_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referreraccount',
            name='referrer_type',
            field=models.CharField(choices=[('doctor', 'Doctor / Medical Professional'), ('hospital_employee', 'Authorized Hospital Employee'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('edcc_personnel', 'EDCC Personnel'), ('call_triage', 'EDMAR/EDHO (Call Triage)'), ('his_department', 'HIS Department'), ('admin', 'Administrator'), ('referrer', 'Referrer'), ('department_user', 'Department User')], default='edcc_personnel', max_length=20),
        ),
    ]
