# Generated by Django 6.0.1 on 2026-02-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0016_alter_referreraccount_referrer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('edcc_personnel', 'EDCC Personnel'), ('call_triage', 'EDMAR/EDHO (Call Triage)'), ('his_department', 'HIS Department'), ('view_only', 'View Only (Department Doctor)'), ('admin', 'Administrator'), ('referrer', 'Referrer'), ('department_user', 'Department User')], default='edcc_personnel', max_length=20),
        ),
    ]
