# Generated by Django 6.0.1 on 2026-02-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0017_add_view_only_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referreraccount',
            name='specialties',
        ),
    ]
