# Generated by Django 6.0.1 on 2026-02-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0018_remove_referreraccount_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='referreraccount',
            name='contact_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of contact numbers'),
        ),
        migrations.AddField(
            model_name='referreraccount',
            name='hospital_doh_level',
            field=models.CharField(blank=True, help_text='DOH Level: Primary, Secondary, or Tertiary', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='referreraccount',
            name='hospital_location',
            field=models.CharField(blank=True, help_text='Hospital location (City/Province in Mindanao)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='referreraccount',
            name='hospital_name',
            field=models.CharField(blank=True, help_text='Name of referring hospital', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='referringhospital',
            name='contact_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of contact numbers (hotlines, phone numbers)'),
        ),
        migrations.AddField(
            model_name='referringhospital',
            name='doh_level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='referringhospital',
            name='location',
            field=models.CharField(blank=True, help_text='City/Province (e.g., Surigao, Agusan)', max_length=100, null=True),
        ),
    ]
