# Generated by Django 6.0.1 on 2026-02-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0019_add_department_and_triage_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitinfo',
            name='filled_at',
        ),
        migrations.RemoveField(
            model_name='transitinfo',
            name='filled_by',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('edcc_personnel', 'EDCC Personnel'), ('call_triage', 'EDMAR/EDHO (Call Triage)'), ('admin', 'Administrator'), ('doctor', 'Doctor'), ('referrer', 'Referrer')], default='edcc_personnel', max_length=20),
        ),
    ]
