# Generated by Django 6.0.1 on 2026-02-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0019_referreraccount_contact_numbers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referreraccount',
            name='contact_numbers',
        ),
        migrations.RemoveField(
            model_name='referreraccount',
            name='hospital_doh_level',
        ),
        migrations.RemoveField(
            model_name='referreraccount',
            name='hospital_location',
        ),
        migrations.RemoveField(
            model_name='referreraccount',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='referringhospital',
            name='contact_numbers',
        ),
        migrations.RemoveField(
            model_name='referringhospital',
            name='doh_level',
        ),
        migrations.AddField(
            model_name='referral',
            name='hospital_contact_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of hospital contact numbers'),
        ),
        migrations.AddField(
            model_name='referral',
            name='hospital_doh_level',
            field=models.CharField(blank=True, help_text='DOH Level: Primary, Secondary, or Tertiary', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='hospital_location',
            field=models.CharField(blank=True, help_text='Hospital location in Mindanao', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='referringhospital',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
