# Generated by Django 6.0.2 on 2026-03-02 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0021_add_referrer_profession_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_type', models.CharField(choices=[('fake_patient', 'Fake Patient Information'), ('duplicate', 'Duplicate Referral'), ('false_emergency', 'False Emergency Claim'), ('wrong_hospital', 'Wrong Hospital Information'), ('incomplete_info', 'Deliberately Incomplete Information'), ('system_abuse', 'System Abuse'), ('spam', 'Spam/Test Referral'), ('other', 'Other Suspicious Activity')], max_length=50)),
                ('reason', models.TextField(help_text='Reason for reporting this referral as fraudulent')),
                ('evidence', models.TextField(blank=True, help_text='Additional evidence or details', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('confirmed', 'Confirmed Fraud'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes on the review', null=True)),
                ('action_taken', models.CharField(blank=True, help_text='Action taken by admin', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_reports', to='referrals.referral')),
                ('reported_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_reports_received', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fraud Report',
                'verbose_name_plural': 'Fraud Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
