# Generated by Django 6.0.1 on 2026-02-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0021_referreraccount_contact_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='vital_signs_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Vital Signs Taken'),
        ),
    ]
