# Generated by Django 6.0.1 on 2026-02-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0022_referral_vital_signs_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referrer_cellphone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
