# Generated by Django 6.0.1 on 2026-03-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0022_migrate_referrer_profession_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitinfo',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks before submitting transit form', null=True),
        ),
    ]
