# Generated by Django 6.0.2 on 2026-02-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0012_referral_transferred_at_referral_transferred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of hospital contact numbers'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_doh_level',
            field=models.CharField(blank=True, help_text='DOH Level: primary, secondary, or tertiary', max_length=20, null=True),
        ),
    ]
