# Generated by Django 6.0.2 on 2026-02-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0024_userprofile_contact_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hospital_barangay',
            field=models.CharField(blank=True, help_text='Barangay', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_district',
            field=models.CharField(blank=True, help_text='District', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_province',
            field=models.CharField(blank=True, help_text='Province', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hospital_street',
            field=models.CharField(blank=True, help_text='Street address', max_length=200, null=True),
        ),
    ]
