# Generated by Django 6.0.2 on 2026-02-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0025_userprofile_hospital_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hospital_region',
            field=models.CharField(blank=True, help_text='Region', max_length=100, null=True),
        ),
    ]
