# Generated by Django 6.0.1 on 2026-02-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0026_userprofile_hospital_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_view_only',
            field=models.BooleanField(default=False, help_text='User can only view, not modify data'),
        ),
    ]
