# Generated by Django 6.0.1 on 2026-03-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0026_cleanup_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='referringhospital',
            name='barangay',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='referringhospital',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='referringhospital',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referringhospital',
            name='doh_level',
            field=models.CharField(blank=True, help_text='Primary, Secondary, or Tertiary', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='referringhospital',
            name='province',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='referringhospital',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='referringhospital',
            name='street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_triage', 'In Triage'), ('waiting_acceptance', 'Waiting Department Acceptance'), ('awaiting_triage_verification', 'Awaiting Triage Verification'), ('dispositioned', 'Dispositioned'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('edcc_personnel', 'EDCC Personnel'), ('call_triage', 'EDMA/EDHO (Call Triage)'), ('admin', 'Administrator'), ('doctor', 'Doctor'), ('referrer', 'Referrer')], default='edcc_personnel', max_length=20),
        ),
    ]
