# Generated by Django 6.0.2 on 2026-03-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0023_referralreport'),
        ('referrals', '0027_add_hospital_address_fields'),
    ]

    operations = [
    ]
