# Generated by Django 6.0.2 on 2026-03-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0028_merge_20260305_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='hospital_barangay',
            field=models.CharField(blank=True, help_text='Hospital barangay name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='hospital_city',
            field=models.CharField(blank=True, help_text='Hospital city/municipality name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='hospital_district',
            field=models.CharField(blank=True, help_text='Hospital district (if applicable)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='hospital_doh_level',
            field=models.CharField(blank=True, help_text='DOH hospital level (primary/secondary/tertiary)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='hospital_province',
            field=models.CharField(blank=True, help_text='Hospital province name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='hospital_region',
            field=models.CharField(blank=True, help_text='Hospital region name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='hospital_street',
            field=models.CharField(blank=True, help_text='Hospital street address', max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='ReferralReport',
        ),
    ]
