# Generated by Django 6.0.1 on 2026-03-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0031_add_referrer_contact_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='vital_signs_date',
            field=models.DateField(blank=True, help_text='Date when vital signs were taken', null=True, verbose_name='Vital Signs Date'),
        ),
        migrations.AddField(
            model_name='referral',
            name='vital_signs_time',
            field=models.TimeField(blank=True, help_text='Time when vital signs were taken', null=True, verbose_name='Vital Signs Time'),
        ),
    ]
