# Generated by Django 6.0.2 on 2026-03-16 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0032_referral_vital_signs_date_referral_vital_signs_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='fraud_last_evaluated_at',
            field=models.DateTimeField(blank=True, help_text='When fraud/spam risk was last evaluated', null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='fraud_requires_manual_review',
            field=models.BooleanField(default=False, help_text='Whether referral should be manually reviewed by EDCC/EDMA due to fraud risk'),
        ),
        migrations.AddField(
            model_name='referral',
            name='fraud_risk_flags',
            field=models.JSONField(blank=True, default=list, help_text='Triggered fraud/spam detection rules'),
        ),
        migrations.AddField(
            model_name='referral',
            name='fraud_risk_level',
            field=models.CharField(choices=[('low', 'Low Possibility'), ('medium', 'Medium Possibility'), ('high', 'High Possibility')], default='low', help_text='Low/Medium/High possibility that referral is spam/fraud', max_length=10),
        ),
        migrations.AddField(
            model_name='referral',
            name='fraud_risk_score',
            field=models.IntegerField(default=0, help_text='Rule-based fraud/spam risk score (0-100)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_referrer_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referrer_suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referrer_suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReferralFraudAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('auto_evaluated', 'Auto Evaluated'), ('mark_safe', 'Mark Safe'), ('keep_flagged', 'Keep Flagged'), ('suspend_referrer', 'Suspend Referrer')], max_length=30)),
                ('previous_risk_level', models.CharField(blank=True, max_length=10, null=True)),
                ('new_risk_level', models.CharField(blank=True, max_length=10, null=True)),
                ('previous_requires_manual_review', models.BooleanField(default=False)),
                ('new_requires_manual_review', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(default=0)),
                ('flags_snapshot', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_audit_logs', to='referrals.referral')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
