# Generated by Django 6.0.1 on 2026-03-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0033_referral_fraud_last_evaluated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referrer_cellphone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
