# Generated by Django 6.0.1 on 2026-03-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0039_remove_referral_contact_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referrer_cellphone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='referral',
            name='working_impression',
            field=models.TextField(verbose_name='Initial Impression'),
        ),
    ]
