# Generated by Django 6.0.3 on 2026-03-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0040_add_userprofile_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('patient_hama', 'Patient went HAMA (Home Against Medical Advice)'), ('patient_expired', 'Patient Expired'), ('patient_opted_stay', 'Patient Opted to Stay at Facility'), ('referred_tertiary', 'Referred to Nearest Tertiary Hospital'), ('patient_scheduled_opd', 'Patient Scheduled for OPD'), ('referral_sent_in_error', 'Referral Sent in Error'), ('duplicate_referral', 'Duplicate Referral'), ('patient_condition_improved', 'Patient Condition Improved'), ('no_available_specialist', 'No Available Specialist at SPMC'), ('others', 'Others')], help_text='Reason for cancelling the referral', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='cancellation_reason_other',
            field=models.TextField(blank=True, help_text="Custom reason if cancellation_reason is 'others'", null=True),
        ),
    ]
